export enum ActionTypes {
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  LOGOUT = "LOGOUT",
}
